### ISSUE TITLE
Refactor letters in Songs

### ISSUE THREAD

**Issue by MichaelCurrin** [nimiology/Musicstreamingservice#4]
Instead of having a long list of characters, use something builtin in

```python
import string

string.ascii_letters
# 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

letters_str = string.ascii_letters + string.digits
# 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

letters = letters_str.split("")
# [ "a", "b", ... ]
```

**Comment by MichaelCurrin** [comment]
https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/python/strings/constants.html

**Comment by nimiology** [comment]
Thanks
but there was a problem
<pre>letters = letters_str.split("")</pre>
this code didn't work 
so I replaced with this 
<pre>import string

letters_str = string.ascii_letters + string.digits
letters = list(letters_str)</pre>

**Comment by MichaelCurrin** [comment]
Oops. Glad you figured it out. I've updated my notes as well to reflect

**Comment by nimiology** [comment]
Nice

**Comment by MichaelCurrin** [comment]
I see you updated a file - looks like the filename is a typo for `utilities.py`

And `slug_generator` as a typo fix. Even `slug` is sufficient.

---
You can optimize the slug with a list comprehension which will use underlying optimized C code rather than Python code.

And constant variables moved to global level.

```python
LETTERS_STR = string.ascii_letters + string.digits
LETTERS = list(letters_str)

def slug(length=101):
    return "".join(random.choice(LETTERS) for _ in range(length))
```



---

OR event better use `random.choices` instead of `random.choice`.

```python
LETTERS_STR = string.ascii_letters + string.digits

def slug(length=101):
    return "".join(random.choices(LETTERS_STR) k=length))
```


---

range includes `0` by default, so just `range(length)` and not `range(0, length)`.


```
>>> list(range(10))
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by MichaelCurrin** [comment]
You should also check the Django API docs to see what functions exist to generate a random slug or to convert say a titlecase string into a slug.

**Comment by nimiology** [comment]
didn't work
```
LETTERS_STR = string.ascii_letters + string.digits
LETTERS = list(letters_str)

def slug(length=101):
    return "".join(random.choices(letters) k=length))
```

**Comment by MichaelCurrin** [comment]
Well `letters` is not going to be valid.

And LETTERS_STR as a string rather than list will work, based on my testing yesterday so do that.

https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/python/random.html#strings

I fixed my example in my comment

**Comment by nimiology** [comment]
Yeah ,
I saw that, Thanks.
